[tool.poetry]
name = "gargle"
version = "0.1.0"
description = ""
authors = ["DeviousStoat <devious@stoat.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.pyright]
strict = ["**/*"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
